# Generated by Django 3.2.6 on 2021-08-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scrape', '0002_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='connectionList',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=132, null=True, unique=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=132, null=True)),
                ('score', jsonfield.fields.JSONField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('profile_url', models.URLField(null=True)),
                ('user_name', models.CharField(max_length=132, null=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrape.connectionlist')),
            ],
        ),
    ]
