# Generated by Django 3.2.6 on 2021-08-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrape', '0003_connection_connectionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
