# Generated by Django 3.2.6 on 2021-08-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrape', '0005_auto_20210816_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='score',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
