# Generated by Django 3.2.6 on 2021-08-19 17:51

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Scrape', '0006_alter_connection_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='score',
            field=jsonfield.fields.JSONField(default={'edu_score': {}, 'work_score': {}}),
            preserve_default=False,
        ),
    ]
