# Generated by Django 3.2.6 on 2021-08-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrape', '0007_alter_connection_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionlist',
            name='Name',
            field=models.CharField(max_length=132, null=True),
        ),
    ]
