# Generated by Django 3.2.6 on 2021-08-23 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scrape', '0008_alter_connectionlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='connection',
            name='score',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='TempList',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('url', models.URLField(null=True)),
                ('status', models.CharField(max_length=132, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132, null=True)),
                ('score', jsonfield.fields.JSONField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('url', models.URLField(null=True)),
                ('username', models.CharField(max_length=132, null=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrape.templist')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduCutOut', models.IntegerField(default=6, null=True)),
                ('workCutout', models.IntegerField(default=6, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
