# Generated by Django 3.2.6 on 2021-08-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrape', '0009_auto_20210823_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='timeDelay',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileimage',
            field=models.URLField(null=True),
        ),
    ]
