# Generated by Django 3.2.6 on 2021-08-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrape', '0011_alter_config_timedelay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tempconnections',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
